
import AppPackage.AnimationClass;
import java.awt.event.KeyEvent;

public class Game extends javax.swing.JFrame {
    AbstractDemon d[];
    
    AnimationClass ac= new AnimationClass();
    
    public Game() {
        initComponents();
        d = new AbstractDemon[8];
        d[0]= new Demon();
        lbld1.setVisible(false);
        lbld2.setVisible(false);
        lbld3.setVisible(false);
        lbld4.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbigd = new javax.swing.JLabel();
        lbld1 = new javax.swing.JLabel();
        lbld2 = new javax.swing.JLabel();
        lbld3 = new javax.swing.JLabel();
        lbld4 = new javax.swing.JLabel();
        btnwave1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblscore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 900));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setPreferredSize(new java.awt.Dimension(1200, 900));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        lblbigd.setBackground(new java.awt.Color(255, 51, 51));
        lblbigd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Big demon.png"))); // NOI18N
        lblbigd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbigdMousePressed(evt);
            }
        });
        getContentPane().add(lblbigd);
        lblbigd.setBounds(120, 440, 120, 60);

        lbld1.setBackground(new java.awt.Color(204, 204, 204));
        lbld1.setOpaque(true);
        lbld1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbld1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbld1MousePressed(evt);
            }
        });
        getContentPane().add(lbld1);
        lbld1.setBounds(20, 20, 120, 60);

        lbld2.setBackground(new java.awt.Color(204, 204, 204));
        lbld2.setOpaque(true);
        getContentPane().add(lbld2);
        lbld2.setBounds(60, 280, 120, 60);

        lbld3.setBackground(new java.awt.Color(204, 204, 204));
        lbld3.setOpaque(true);
        getContentPane().add(lbld3);
        lbld3.setBounds(260, 290, 120, 60);

        lbld4.setBackground(new java.awt.Color(204, 204, 204));
        lbld4.setOpaque(true);
        getContentPane().add(lbld4);
        lbld4.setBounds(340, 410, 120, 60);

        btnwave1.setText("Press to Start Wave 1");
        btnwave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwave1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnwave1);
        btnwave1.setBounds(330, 170, 160, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Score:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 820, 40, 20);

        lblscore.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblscore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblscore);
        lblscore.setBounds(70, 820, 34, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int check(){
        String ia, ib, ic, id;
        ia = ""+lbld1.getIcon();
        ib = ""+lbld2.getIcon();
        ic = ""+lbld3.getIcon();
        id = ""+lbld4.getIcon();
        //compare the labels to what icon they have in them to see if they are empty
        if (!(ia.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Big%20demon.png")) && !(ia.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Small%20demon.png"))){
            return 1;
        }
        else if (!(ib.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Big%20demon.png")) && !(ib.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Small%20demon.png"))){
            return 2;
        }
        else if (!(ic.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Big%20demon.png")) && !(ic.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Small%20demon.png"))){
            return 3;
        }
        else if (!(id.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Big%20demon.png")) && !(id.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Small%20demon.png"))){
            return 4;
        }
        else return 0;    
    }
  
    public void assign(int id){
        //set demon to empty icon
        //set label location of demon
        if(check()==1){
            lbld1.setIcon(new javax.swing.ImageIcon(getClass().getResource(d[id].getImage())));
            d[id].setlbl(lbld1);
        }
        else if(check()==2){
            lbld2.setIcon(new javax.swing.ImageIcon(getClass().getResource(d[id].getImage())));
            d[id].setlbl(lbld2);
        }
        else if(check()==3){
            lbld3.setIcon(new javax.swing.ImageIcon(getClass().getResource(d[id].getImage())));
            d[id].setlbl(lbld3);
        }
        else if(check()==4) {
            lbld4.setIcon(new javax.swing.ImageIcon(getClass().getResource(d[id].getImage())));
            d[id].setlbl(lbld4);
        }
        
    }
    private void lblbigdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbigdMousePressed
        AnimationClass ac= new AnimationClass();
        ac.jLabelXRight(20, 300, 2, 1, lblbigd);
        ac.jLabelXLeft(300, 20, 2, 1, lblbigd);
        //System.out.println(""+lblbigd.getIcon());
        String ic= ""+lblbigd.getIcon();
        if (ic.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Big%20demon.png")){
            System.out.println("it works");
        }
        
    }//GEN-LAST:event_lblbigdMousePressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    
    }//GEN-LAST:event_formKeyPressed

    private void btnwave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwave1ActionPerformed
        //disable and invisible button so game can be played
        btnwave1.setEnabled(false);
        btnwave1.setVisible(false);
        //make new demon
        d[1]=new Demon(20,20);
        assign(1);
        //line up the label it is in
        d[1].getlbl().setVisible(true);
        d[1].getlbl().setAlignmentX(d[1].getxPos());
        d[1].getlbl().setAlignmentY(d[1].getyPos());
        //move demon
        ac.jLabelXRight(d[1].getxPos(), 1300, 2, 1, d[1].getlbl());
        
        //need to add something to remove pic when past certain point
        
        
    }//GEN-LAST:event_btnwave1ActionPerformed

    private void lbld1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbld1MousePressed
        String id=""+lbld1.getIcon();
        if(id.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Big%20demon.png")){
            d[0].updatescore(10);
            lblscore.setText(""+d[0].score());
        }
        if(id.equals("file:/T:/ISS-ICS4U1-1/jame5380/Unit%205/ISU/build/classes/Small%20demon.png")){
            d[0].updatescore(20);
            lblscore.setText(""+d[0].score());
        }
        lbld1.setVisible(false);
    }//GEN-LAST:event_lbld1MousePressed

    private void lbld1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbld1MouseClicked
        
    }//GEN-LAST:event_lbld1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnwave1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblbigd;
    private javax.swing.JLabel lbld1;
    private javax.swing.JLabel lbld2;
    private javax.swing.JLabel lbld3;
    private javax.swing.JLabel lbld4;
    private javax.swing.JLabel lblscore;
    // End of variables declaration//GEN-END:variables
}
